export const DATABASE_PROVIDER = 'SEQUELIZE';

export const DEFAULT_VALUES = {
  DB_DEFAULT_LIMIT: 100,
  DB_MAX_LIMIT: 1000,
  DB_OFFSET: 0,
};

export const USER_PROVIDER = 'USER_REPOSITORY';
export const AUTHOR_PROVIDER = 'AUTHOR_REPOSITORY';
export const MOVIE_PROVIDER = 'MOVIE_REPOSITORY';
