GET  http://localhost:3000/api/author HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwic3ViIjoiNWY4NzQ5Y2UxYmJkM2QzYzdjYWRmYjZjIiwiaWF0IjoxNjAyNzAxODEwLCJleHAiOjE2MDI3Mzc4MTB9.CgcDYUG4ep4NpGI-XPpO6Mdr2wbmVBoMD94Nw67HZxY

###
GET  http://localhost:3000/api/author/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwic3ViIjoiNWY4NzQ5Y2UxYmJkM2QzYzdjYWRmYjZjIiwiaWF0IjoxNjAyNzAxODEwLCJleHAiOjE2MDI3Mzc4MTB9.CgcDYUG4ep4NpGI-XPpO6Mdr2wbmVBoMD94Nw67HZxY

###

POST http://localhost:3000/api/author HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwic3ViIjoiNWY4NzQ5Y2UxYmJkM2QzYzdjYWRmYjZjIiwiaWF0IjoxNjAyNzAxODEwLCJleHAiOjE2MDI3Mzc4MTB9.CgcDYUG4ep4NpGI-XPpO6Mdr2wbmVBoMD94Nw67HZxY

{
    "firstName": "Кристофер",
    "lastName": "Нолан",
    "gender": "MALE"
}

###

PUT http://localhost:3000/api/author HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwic3ViIjoiNWY4NzQ5Y2UxYmJkM2QzYzdjYWRmYjZjIiwiaWF0IjoxNjAyNzAxODEwLCJleHAiOjE2MDI3Mzc4MTB9.CgcDYUG4ep4NpGI-XPpO6Mdr2wbmVBoMD94Nw67HZxY

{
    "id": 5,
    "firstName": "Стивен",
    "lastName": "Спилберг",
    "gender": "MALE"
}

###

DELETE http://localhost:3000/api/author/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwic3ViIjoiNWY4NzQ5Y2UxYmJkM2QzYzdjYWRmYjZjIiwiaWF0IjoxNjAyNzAxODEwLCJleHAiOjE2MDI3Mzc4MTB9.CgcDYUG4ep4NpGI-XPpO6Mdr2wbmVBoMD94Nw67HZxY
