# Get By authorId
GET  http://localhost:3000/api/movie?authorId=4 HTTP/1.1

###

# Get By movieId
GET  http://localhost:3000/api/movie/1 HTTP/1.1

###

# Create Movie
POST http://localhost:3000/api/movie HTTP/1.1
content-type: application/json

{
    "authorId": 4,
    "title": "Тест для удаления"
}

###

# Update Movie
PUT http://localhost:3000/api/movie HTTP/1.1
content-type: application/json

{
    "authorId": 4,
    "id": 4
}

###

# Delete
DELETE  http://localhost:3000/api/movie/5 HTTP/1.1
content-type: application/json
