POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "test3",
    "password": "testtest3"
}

###

POST http://localhost:3000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "testtest"
}