version: '3'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - nestjs-server
    networks:
      - app-network
  mongo_node22:
    container_name: mongo_node22
    image: 'mongo:latest'
    volumes:
      - /data/db/mongo
    networks:
      - app-network
  nestjs-server:
    container_name: nestjs-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
      - /app/node_modules
    links:
      - mongo_node22
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
